---
abstract: 'Download and deploy jQuery into your webapp'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.9.0, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Setup-Plugin-Assets-JQuery
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Nephia::Setup::Plugin::Assets::JQuery:
    file: lib/Nephia/Setup/Plugin/Assets/JQuery.pm
    version: 0.03
requires:
  File::Copy: 0
  File::Share: 0.03
  Nephia: 0.80
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Setup-Plugin-Assets-JQuery/issues
  homepage: https://github.com/nephia/Nephia-Setup-Plugin-Assets-JQuery
  repository: git://github.com/nephia/Nephia-Setup-Plugin-Assets-JQuery.git
version: 0.03
